### ISSUE TITLE
sqlalchemy: doesn't like get_checked_permissions returning None

### ISSUE THREAD

**Issue by AstraLuma** [osohq/oso#1438]
This seems to happen whenever oso cleans up.

```
  File "/usr/local/bin/flask", line 8, in <module>
    sys.exit(main())
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 967, in main
    cli.main(args=sys.argv[1:], prog_name="python -m flask" if as_module else None)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 586, in main
    return super(FlaskGroup, self).main(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.8/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/cli.py", line 426, in decorator
    return __ctx.invoke(f, *args, **kwargs)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 249, in __exit__
    self.pop(exc_value)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 238, in pop
    self.app.do_teardown_appcontext(exc)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2321, in do_teardown_appcontext
    func(exc)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 899, in shutdown_session
    self.session.remove()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 180, in remove
    if self.registry.has():
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1015, in has
    return self.scopefunc() in self.registry
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_oso/session.py", line 179, in _scopefunc
    checked_permissions = frozenset(get_checked_permissions().items())
AttributeError: 'NoneType' object has no attribute 'items'
```

From the docs:

> * **get_checked_permissions** – Callable that returns an optional map of permissions (resource-action pairs) to authorize for the session. If the callable returns `None`, no authorization will be applied to the session.

**Comment by AstraLuma** [comment]
also

```
Traceback (most recent call last):
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2464, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2458, in wsgi_app
    ctx.auto_pop(error)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 452, in auto_pop
    self.pop(exc)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 438, in pop
    app_ctx.pop(exc)
  File "/usr/local/lib/python3.8/site-packages/flask/ctx.py", line 238, in pop
    self.app.do_teardown_appcontext(exc)
  File "/usr/local/lib/python3.8/site-packages/flask/app.py", line 2321, in do_teardown_appcontext
    func(exc)
  File "/usr/local/lib/python3.8/site-packages/flask_sqlalchemy/__init__.py", line 899, in shutdown_session
    self.session.remove()
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/orm/scoping.py", line 180, in remove
    if self.registry.has():
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy/util/_collections.py", line 1015, in has
    return self.scopefunc() in self.registry
  File "/usr/local/lib/python3.8/site-packages/sqlalchemy_oso/session.py", line 179, in _scopefunc
    checked_permissions = frozenset(get_checked_permissions().items())
AttributeError: 'NoneType' object has no attribute 'items'
```
