### ISSUE TITLE
Python sqlalchemy_oso translate_compare difficult to understand error due to assertion

### ISSUE THREAD

**Issue by kkirsche** [osohq/oso#1552]
When writing queries using `sqlalchemy_oso`, if the `assert not right_path` is hit, a hard to understand error is triggered:

```
ERROR:    Exception in ASGI application
Traceback (most recent call last):
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/uvicorn/protocols/http/httptools_impl.py", line 372, in run_asgi
    result = await app(self.scope, self.receive, self.send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/uvicorn/middleware/proxy_headers.py", line 75, in __call__
    return await self.app(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/fastapi/applications.py", line 261, in __call__
    await super().__call__(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/applications.py", line 112, in __call__
    await self.middleware_stack(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 181, in __call__
    raise exc
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/errors.py", line 159, in __call__
    await self.app(scope, receive, _send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 23, in __call__
    await responder(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/gzip.py", line 42, in __call__
    await self.app(scope, receive, self.send_with_gzip)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 92, in __call__
    await self.simple_response(scope, receive, send, request_headers=headers)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/middleware/cors.py", line 147, in simple_response
    await self.app(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 82, in __call__
    raise exc
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/exceptions.py", line 71, in __call__
    await self.app(scope, receive, sender)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 21, in __call__
    raise e
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/fastapi/middleware/asyncexitstack.py", line 18, in __call__
    await self.app(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 656, in __call__
    await route.handle(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 259, in handle
    await self.app(scope, receive, send)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/routing.py", line 61, in app
    response = await func(request)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 227, in app
    raw_response = await run_endpoint_function(
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/fastapi/routing.py", line 162, in run_endpoint_function
    return await run_in_threadpool(dependant.call, **values)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/starlette/concurrency.py", line 39, in run_in_threadpool
    return await anyio.to_thread.run_sync(func, *args)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/anyio/to_thread.py", line 28, in run_sync
    return await get_asynclib().run_sync_in_worker_thread(func, *args, cancellable=cancellable,
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 818, in run_sync_in_worker_thread
    return await future
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/anyio/_backends/_asyncio.py", line 754, in run
    result = context.run(func, *args)
  File "/Users/username-here/git/docker/projectname-here/api/src/projectname-here/routers/cloud/security_groups/rules.py", line 49, in invalid_ip_security_group_rules_count
    return get_invalid_ip_security_group_rules_count(
  File "/Users/username-here/git/docker/projectname-here/api/src/projectname-here/crud/security_group_rules.py", line 23, in get_invalid_ip_security_group_rules_count
    return cast(int, query.order_by(SecurityGroupRule.id).scalar())
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2888, in scalar
    ret = self.one()
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2865, in one
    return self._iter().one()
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1673, in execute
    result = fn(orm_exec_state)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/session.py", line 311, in do_orm_execute
    filter = authorize_model(oso, user, action, session, entity)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/auth.py", line 95, in authorize_model
    filter = partial_to_filter(
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/partial.py", line 122, in partial_to_filter
    return translate_expr(expression, session, model, get_model)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/partial.py", line 137, in translate_expr
    return translate_and(expression, session, model, get_model)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/partial.py", line 152, in translate_and
    translated = translate_expr(expression, session, model, get_model)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/partial.py", line 131, in translate_expr
    return translate_compare(expression, session, model, get_model)
  File "/Users/username-here/Library/Caches/pypoetry/virtualenvs/projectname-here-259ubUSQ-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/partial.py", line 221, in translate_compare
    assert not right_path
AssertionError
```

When debugging, I wrapped the `assert` in a `try/except`

```python
        try:
            assert not right_path
        except AssertionError as e:
            print(f"{right=}")
            print(f"{right_path=}")
            raise e from e
```

and see that right and right path are:

```
right=Expression(Dot, [Expression(And, [Expression(Isa, [Variable('_this'), Pattern(SecurityGroup, {})]), Expression(Unify, [Expression(Dot, [Expression(And, [Expression(Isa, [Variable('_this'), Pattern(Platform, {})]), Expression(Unify, ['core', Expression(Dot, [Variable('_this'), 'name'])])]), 'name']), Expression(Dot, [Variable('_this'), 'platform_name'])])]), 'inventory_id'])
right_path=('inventory_id',)
```

**Comment by kkirsche** [comment]
Fixed it. The error could read something like:

I'd recommend something like this:

```
try:
   assert not right_path
expect AssertionError as e:
   raise PolicyError("Invalid comparison in policy. This may be caused by comparing the foreign key field rather than the relationship property") from e

**Comment by gj** [comment]
That's a great suggestion @kkirsche — would you be up for a PR?

**Comment by kkirsche** [comment]
Happy to, @gj. Is there an existing exception class you would like me to use to raise this or would you like me to create a new exception for this? I want to make sure to avoid unnecessary code review cycles over something small like that.

**Comment by gj** [comment]
@kkirsche a `PolarRuntimeError` is probably fine for this one

https://github.com/osohq/oso/blob/0f234836133ab198e479fad90df7470690e0bec0/languages/python/oso/polar/exceptions.py#L36

**Comment by kkirsche** [comment]
Merge request submitted, though I didn't see a CHANGELOG file to update per the checklist — thanks!
