### ISSUE TITLE
Python `sqlalchemy_oso.sqlalchemy_utils:97` can trigger recursion error

### ISSUE THREAD

**Issue by kkirsche** [osohq/oso#1579]
There seems to be a loop possibility in 

https://github.com/osohq/oso/blob/main/languages/python/sqlalchemy-oso/sqlalchemy_oso/sqlalchemy_utils.py#L97

I would need to see if I can extract sufficient code to create a reproduction of this, but wanted to at least share it in case the Oso team may know why this would occur.

Traceback:

```python
Traceback (most recent call last):
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/flask/app.py", line 1523, in full_dispatch_request
    rv = self.dispatch_request()
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/flask/app.py", line 1509, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/middleware/iam.py", line 110, in wrapper
    return f(*args, **kwds)
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/views/v1/resource_type/request.py", line 163, in get_all_open_requests_for_resource_type
    return controller.get_all_open_requests_paginated()
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/middleware/server_timing_api.py", line 173, in wrapper
    return f(*args, **kwds)
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/controllers/v1/resource_type/request.py", line 323, in get_all_open_requests_paginated
    paginated_requests = get_paginated_open_requests(
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/authorization/authorization_initialization.py", line 65, in wrapper
    return func(*args, **kwargs)
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/crud/request.py", line 83, in get_paginated_open_requests
    return PaginationParameters.paginate_query_from_request(
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/schemas/v1/pagination.py", line 259, in paginate_query_from_request
    return instance.paginate_query(sort_by_model, query)
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/schemas/v1/pagination.py", line 294, in paginate_query
    else paginate(
  File "/Users/kkirsche/git/docker/REDACTED/api/src/REDACTED/utilities/pagination.py", line 64, in paginate
    items = query.limit(per_page).offset((page - 1) * per_page).all()
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2768, in all
    return self._iter().all()
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/query.py", line 2903, in _iter
    result = self.session.execute(
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy/orm/session.py", line 1693, in execute
    result = fn(orm_exec_state)
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/session.py", line 299, in do_orm_execute
    entities = all_entities_in_statement(execute_state.statement)
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/sqlalchemy_utils.py", line 36, in all_entities_in_statement
    entities |= default_load_entities(entities)
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/sqlalchemy_utils.py", line 97, in default_load_entities
    default_entities |= default_load_entities([rel.mapper])
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/sqlalchemy_utils.py", line 97, in default_load_entities
    default_entities |= default_load_entities([rel.mapper])
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/sqlalchemy_utils.py", line 97, in default_load_entities
    default_entities |= default_load_entities([rel.mapper])
  [Previous line repeated 949 more times]
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy_oso/sqlalchemy_utils.py", line 92, in default_load_entities
    for rel in relationships.values():
  File "/Users/kkirsche/Library/Caches/pypoetry/virtualenvs/REDACTED--kEzOSes-py3.10/lib/python3.10/site-packages/sqlalchemy/util/_collections.py", line 211, in values
    return list(self._data.values())
RecursionError: maximum recursion depth exceeded while calling a Python object
```

The paginate class referenced is the FlaskSQLAlchemy Pagination helper:

https://github.com/pallets-eco/flask-sqlalchemy/blob/818c947b665206fe8edd8c1680b18ce83d3e4744/src/flask_sqlalchemy/__init__.py#L478

If I add a print statement like so in your library:

```python
                if rel.lazy == "joined":
                    print(default_entities, rel.mapper)
                    default_entities |= default_load_entities([rel.mapper])
                    default_entities.add(rel.mapper)
```

I see that it's looping over (seemingly) a single model:

```
set() mapped class User->REDACTED2_users
{<Mapper at 0x1097ccfa0; User>} mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
set() mapped class Category->REDACTED_categories
...
set() 2022-06-08 22:57.15 [error    ] A problem occurred while processing the request error=RecursionError('maximum recursion depth exceeded while getting the str of an object') status=500 Internal Server Error traceback=Traceback (most recent call last):
```

Any help understanding understanding what this function is doing and how I can debug it to locate what an appropriate patch is would be greatly appreciated.

**Comment by kkirsche** [comment]
Thinking about this more, I'll look today and see if this is related to self-referencing models. 

In this case categories can have a parent category of the same type, thus probably creating this loop since it's not checking if it already knows the entity

**Comment by kkirsche** [comment]
This seems like part of it, but the method still seems to be looping incorrectly. Continuing to look into it :(
